# Generated by Django 5.2.7 on 2025-11-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblio', '0002_utilisateur_adresse_utilisateur_date_inscription_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentaire',
            unique_together={('utilisateur', 'livre')},
        ),
    ]
