# Generated by Django 5.2.7 on 2025-11-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblio', '0003_alter_commentaire_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('RENDU', 'Rendu'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=10),
        ),
    ]
